#!/bin/bash
clear
figlet -f small -tc "YOUTUBE MUSIC DOWNLOADER"

file1=`cat ytmsdl-txt.txt`  
echo "$file1" 


echo "Enter the format and link : "
read var1 var2
youtube-dl -o '/data/data/com.termux/files/home/storage/shared/YTMSDL/%(title)s.%(ext)s​' --extract-audio --audio-format $var1 $var2

echo "Download Complete"

